spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: rmfls1234!
    url: jdbc:mariadb://3.36.74.17:3306/BULLTI
    username: root
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true