spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: rmfls1234!
    url: jdbc:mariadb://database-1.clxa5chqlggv.ap-northeast-2.rds.amazonaws.com:3306/MyDB
    username: choi
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    me.silvernine: DEBUG